### ISSUE TITLE
浏览器报错

### ISSUE THREAD

**Issue by bazhuaa** [keptab/keptab#35]
求助！使用了一段时间后，突然打不开了，以前保存了很多网站在该插件里
谷歌浏览器出现了以下错误：
service_worker.js:2 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.<anonymous> (chrome-extension://feodekcipceogpeomnijgmdlmocbggbi/service_worker.js:2:1136)
    at q (chrome-extension://feodekcipceogpeomnijgmdlmocbggbi/service_worker.js:2:12815)
    at async chrome-extension://feodekcipceogpeomnijgmdlmocbggbi/service_worker.js:2:14766
    at async te (chrome-extension://feodekcipceogpeomnijgmdlmocbggbi/service_worker.js:2:14750)

**Comment by mywaiting** [comment]
你好，这是整个插件 IndexedDB 数据库丢失了，请参考如下方法：

1、如果之前有下载过/导出过数据，请重新安装插件后重新导入数据
2、如果先前没有下载过/导出过数据，请前往插件的选项页面，使用【数据灾难导出】能否导出部分数据，如果能导出数据，请重新安装插件后重新导入数据即可

希望对你有用 @bazhuaa
